### ISSUE TITLE
Could yig support new backend such as seaweedfs?

### ISSUE THREAD

**Issue by thesues** [journeymidnight/yig#70]

**Comment by cannium** [comment]
TODO list(order to be determined)
- [ ] Storage backend as plugin #142
- [ ] Basic functionality for seaweedfs backend #143
- [ ] Feature-complete seaweedfs backend #144
- [ ] Adjust CI for the new backend #145

**Comment by chrislusf** [comment]
I am working on SeaweedFS. Just let me know if I can help anything here.

**Comment by cannium** [comment]
Thanks for your kindly offered help. Meanwhile, the yig community is moving forward to a new storage backend, which you might want to check [here](https://github.com/journeymidnight/autumn). Hopefully you would share your thoughts and ideas with us there.

**Comment by chrislusf** [comment]
This `autumn` project seems still young but trying to do a lot of things. Most designs look fine or maybe easy to prototype, but they all take non-trivial amount of time to stabilize. 

Also try to have a clear differentiator. 

btw: ETCD is not really scalable. SeaweedFS can use ETCD but not for large deployments as reported by users.
https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores
